### ISSUE TITLE
How exactly can I run this proxy on my local enviornment

### ISSUE THREAD

**Issue by Kaitou786** [mshick/add-pr-comment-bot#1]
Hi, I like the way this handles the comment from fork PR, but I'm confused how can I setup the proxy server to run on my local system, or on aws or openshift, Couldn't find anything on the README, any would be great in this matter.

**Comment by mshick** [comment]
I've set it up to run on Cloud Run because it's likely free for most users, and allows for the deploy button which makes it extremely easy to get running. I imagine folks wanting to run this server to do a specific job, but maybe they aren't interested in maintaining cloud infrastructure.

As far as running it locally — it's a standard Node.js / Express app, and you could run it locally by defining the required env variable and running the npm start script, e.g.,

```
$ GITHUB_TOKEN=xxx111yyy npm run start
```

If you wanted to submit a PR for docs or files to allow deployment on other cloud services I'd be happy to review.
